language: python

python:
  - "2.7"
  - "3.6"

cache:
  directories:
    - .pip_download_cache

env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/cloudaux/tests/gcp/fixtures/testkey.json


install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    - pkelley@netflix.com
    - mgrima@netflix.com
